function sc = ApplyDetector(Cparams, ii_im, mu, sigma)
    if(nargin<=2)
        mu=0;
        sigma=1;
    end

    %ONELINEEERRR!!!! AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHH
    sc=  ...
    ( ...
        ( ...
            Cparams.ps' ...
            .* ...
            VecComputeFeature( ... %1x32
                ii_im', ... %Cparams.fmat(:,Cparams.Thetas(:,2)) ... %selected_fmats
                VecFeatureNormalized( ...
                    Cparams.all_ftypes( ...
                        Cparams.Thetas(:,2) ...
                    ,:), ...
                    mu, ...
                    sigma, ...
                    20, ...
                    20 ...
                ) ... %is W,H correct ?
            ) ...
        ) ...
        < ...
        ( ...
            Cparams.ps ...
            .* ...
            Cparams.Thetas(:,1) ...
        )' ...
    ) ...
    * ...
    Cparams.alphas;