function sc = ApplyDetector(Cparams,ii_im)
    %ONELINEEERRR!!!! AAAAAAAAAHHHH
    sc=  ...
    ( ...
        ( ...
            Cparams.ps' ...
            .* ...
            VecComputeFeature( ... %1x32
                ii_im, ...
                Cparams.fmat(:,Cparams.Thetas(:,2)) ... %selected_fmats
            ) ...
        ) ...
        < ...
        ( ...
            Cparams.ps ...
            .* ...
            Cparams.Thetas(:,1) ...
        )' ...
    ) ...
    * ...
    Cparams.alphas;
